### ISSUE TITLE
Lab 3

### ISSUE THREAD

**Issue by tnt2501** [Watts-College/paf-510-template#11]
Hello professor,

For some of the questions on the lab it asks to regress x on y while saving the residuals, and to then create a scatterplot.
Below this is R code chunk that has the regression and seems to have the residuals already saved. 

Are these questions just asking to compare the scatterplots already coded in the lab templets to the scatterplot in question 1? 

Or am I missing something throughout this process. 

Thank you!

**Comment by youngjaewon** [comment]
Hi Tyler,

Yes, you don't need to write new R scripts; just use the R scripts provided and explain the difference between scatterplots.
