### ISSUE TITLE
Lab 4 

### ISSUE THREAD

**Issue by leachapman019** [Watts-College/paf-510-template#13]
Hello!
When I try to run the file it says this:
Error in .stargazer.wrap(..., type = type, title = title, style = style,  : 
  object 'm.auxiliary' not found
I'm not sure if this is related to the other question but how do I resolve this issue? Thank you,
Lea

**Comment by youngjaewon** [comment]
@leachapman019 

The error message suggests that the object 'm.auxiliary' is not defined or does not exist in your R environment when you try to use it with the stargazer function. To resolve this issue, you should make sure that the 'm.auxiliary' object is defined.

Youngjae
