### ISSUE TITLE
Lab04

### ISSUE THREAD

**Issue by tnt2501** [Watts-College/paf-510-template#14]
Hello,

To calculate how good the naive estimation is for B1 (In Q1 part 3), would I take the bias of the auxiliary regression (answer from part 2) and divide that by B1 from the full model?

**Comment by youngjaewon** [comment]
Hi Tyler, 
@tnt2501 
Yes, please report the bias/B1.

**Comment by tnt2501** [comment]
Thanks for the response professor. 

Also, I am stuck on Q2 part 3.  The question is asking what must be true about the sign of the correlation between RSE and CSE to get these results. But α1 equals the correlation of RSE and CSE. 

In the chart below this question, it already shows the signs for α1⋅B2 = sign of Bias. 

I am confused on what the question is asking, what am I missing here?

**Comment by youngjaewon** [comment]
@tnt2501 

You need to indicate whether α1 and B2 are positive or negative and also specify the sign of Bias. The chart below shows four possible combinations of Bias signs based on the signs of α1 and B2. Please pick the correct combination based on the signs of α1 and B2 in the given example.
