### ISSUE TITLE
Lab #6

### ISSUE THREAD

**Issue by jasminacosta** [Watts-College/paf-510-template#16]
Hi Professor! 

For part 2 I have questions on #3 and #4. 

For #3 is the step to only use the exp( ) function and place the number given inside of the function? 
Also, what does that function do? Since I am having a hard time understanding that.

For #4 this equation is given log(Salary)=6.367+0.343⋅log(Revenue), but the numbers are slightly different in the table below it. 
Are we supposed to use this equation with those numbers? Or the numbers from the table to make the equation?

Another question, I went ahead to just try it in the equation given and I placed (log(14.44879) in the revenue portion of the equation and received an output. Then I used the exp( ) function with the output that I got and got what I would assume is the typical salary for a director of an averaged-size nonprofit. I am just confused on whether I am taking the right steps to making these calculations.

Thank you!

**Comment by youngjaewon** [comment]
Hi Jasmin,

For #3, The exp function reverses logged values back to their original values. For example, if you have log(3.00) = 1.1, then exp(1.1) = 3.00.

For #4, you can use either option. I will consider answers using either of them as correct. I apologize for the confusion.

You followed the correct approach. Replace log(Revenue) with 14.44 in this equation: log(Salary) = 6.367 + 0.343 * log(Revenue) = 6.367 + 0.343*14.44. This will yield a value for log(Salary). Then, use the exp function to convert the logged Salary into normal dollars.

**Comment by jasminacosta** [comment]
Thank you for the clarification Professor!
