### ISSUE TITLE
Lab 6

### ISSUE THREAD

**Issue by tnt2501** [Watts-College/paf-510-template#17]
Hello professor,

In lab 6 Q1 when running the regression with the new variable my summary isn't producing a nice clean chart, similar to what is in the lab notes.

Instead my summary results are all smushed together in my R markdown. 
Is there a way or a code I am missing to make the formatting more readable? 

Thanks

**Comment by youngjaewon** [comment]
Hi Tyler, can you send me your R code so that I can take a look?

***@***.***

**Comment by tnt2501** [comment]
Hello Professor I actually figured it out. I believe it was due to the placements of code within the R chucks,
BUT
I can not save my file as html. It is only giving me the option for rmd

Any idea why this might be happening?

**Comment by tnt2501** [comment]
Hi professor,

Thankful with some trial and error I was able to resolve the issue in regard to the html format!

**Comment by youngjaewon** [comment]
Good to know that you resolved the issue. Please send me via email the RMD file if you have any additional issues.
