### ISSUE TITLE
Course Instructor Clarification

### ISSUE THREAD

**Issue by epigsci00** [Watts-College/paf-510-template#18]
Is this course led by Anthony Howell, David Schlinkert, or Jason Sills?

I have seen each of those individuals listed as the instructor for this course on various course materials provided on Canvas and Github.

**Comment by AntJam-Howell** [comment]
@epigsci00 just sent you an email. 
Best

**Comment by youngjaewon** [comment]
@epigsci00 
I instructed this course during the fall semester of 2023.

Youngjae Won
Ph.D. Candidate
School of Public Affairs | Arizona State University
Center on Technology, Data and Society ([CTDS](https://techdatasociety.asu.edu/))
