### ISSUE TITLE
Lab 2-Confidence Intervals

### ISSUE THREAD

**Issue by KaytieS** [Watts-College/paf-510-template#23]
@AntJam-Howell I'm confused with the confidence interval formula, what is t in the formula? 
Edit: I actually found the t value but I am now wondering for question 1 are we just giving the value for the standard error or do we explain it? 
Also, I am not really understanding question 6. Using the values given in the formula you get the slope for model 1 but it's asking about model 4. And I'm not sure how to interpret the pairs plot?

**Comment by AntJam-Howell** [comment]
Hi @KaytieS, 

For question 1, all you need is to just give the value of the standard error of b1
 in Model-01. no explanation required. 

For question 6, the main idea is to understand whether or not the formula used to obtain the slope for b1 in a simple linear regression can be used to calculate the slope of b1 in a multiple linear regression.  In other words, once you start adding additional control variables do you expect the slop to change or not as you move from simple regression to multiple regression.  if you expect to change, and you should, a more complicated formula is needed to calculate the new slope of b1 that better takes into account the inclusion of other control variables. 

The pairs plot and correlations is jut meant for visualizing aid this week, we dig more into that next week and it will become more clear.
