### ISSUE TITLE
Lab-02 Submissions

### ISSUE THREAD

**Issue by tmottjoy** [Watts-College/paf-510-template#25]
I just want to clarify that we have to submit two files for lab 2?

I'm able to submit the .rmd file, but I keep getting an error when I try knitting to HTML and I'm not sure how to work around it or absolve the problem.

![R HTML Error](https://github.com/Watts-College/paf-510-template/assets/155856089/76fc98ec-6819-4d64-bc66-142a7608bf77)

**Comment by ngipe7** [comment]
@tmottjoy Did you install the Stargazer package in R Studio?
install.packages("stargazer")

**Comment by tmottjoy** [comment]
> @tmottjoy Did you install the Stargazer package in R Studio? install.packages("stargazer")

I definitely did not, and just figured it out. Thank you!
