### ISSUE TITLE
Lab 3 Part 2 

### ISSUE THREAD

**Issue by johndano** [Watts-College/paf-510-template#27]
@AntJam-Howell Good afternoon,

I had a question about the wording for Part 2 for the lab.

It's asking which control variable would change the slope of caffeine if removed from the model. The wording is throwing me off a little but I am assuming this question is asking which control variable would affect the Unexplained portions?

![Screenshot 2024-01-25 143156](https://github.com/Watts-College/paf-510-template/assets/156475252/81f7db14-c3f9-412a-a15b-e5d200f35fd9)

**Comment by AntJam-Howell** [comment]
Hi @johndano, 
good question: I would say that the question is asking which of the control variables, when excluded, would most significantly alter the estimated effect (slope) of caffeine on the outcome variable in the regression model. Essentially, it seeks to identify which control variable has the strongest confounding effect on the relationship between caffeine and the outcome.

**Comment by KaytieS** [comment]
@AntJam-Howell to go off of this question, I am getting confused with the first part that asks about which would change the slope of caffeine if removed. I know that the stress index is correlated with caffeine which means it changes the slope but since the model has 2 control variables, I'm confused whether that means that removing the stress index variable from the model would change the slope more or if removing the gym time variable would change the slope since then the stress index is still a part of the model and affecting the slope more?

**Comment by swest235** [comment]
@KaytieS @AntJam-Howell Hey Kaytie, so unless my understanding is wrong, the control variable with the highest correlation to the policy variable (caffeine) is what will change the slope the most. So if you look at the panel chart whatever it is that shows the variables and caffeine, you'll see that caffeine and stress.index have a .99 correlation, whereas caffeine and gymtime have a -0.037. Therefore, unless I'm misunderstanding, stress.index is the only highly correlated control. 

Professor Sills, I wanted to make sure the second half of the Part II questions were indeed what I understood it to be. "Which would result in a larger standard error associated with caffeine if removed from the model?" 

That is asking which variable is not correlated with caffeine basically, right?

**Comment by AntJam-Howell** [comment]
Hi @KaytieS 
Echoing what @swest235 said: The question is exploring which control variable has a more substantial confounding influence on the relationship between caffeine consumption and the outcome. If the stress index has a high correlation with caffeine and the outcome, removing it from the model would likely alter the slope of caffeine more significantly than removing gym time, assuming gym time has a weaker correlation. In other words, the control variable with the stronger correlation to both caffeine and the outcome is the one whose removal would most change the slope of caffeine in the model.

@swest235 yes, that is correct. 
Best
