### ISSUE TITLE
Lab #2

### ISSUE THREAD

**Issue by jasminacosta** [Watts-College/paf-510-template#3]
Hi Professor, I had an issue when it came to submitting Lab #2. 

When I went to submit the rmd file it removed my drawings of the confidence interval graphs that were made in R, but they show up on the html file.

Does that need to be resolved and if so, how can I fix that?

Thank you!

**Comment by youngjaewon** [comment]
@jasminacosta 
I just checked the files you submitted. You don't need to fix it because I can see the figures in the HTML file.

**Comment by jasminacosta** [comment]
Great, thank you!
