### ISSUE TITLE
Lab 4 - Missing question in rmd file?

### ISSUE THREAD

**Issue by swest235** [Watts-College/paf-510-template#32]
@AntJam-Howell the rmd for lab 4 does not list a question that the lab 4 instructions do. I'm assuming we are going off what is in the actual rmd file? This is also the case for question 2, are all these instances simply reflective?

I'm also curious, at what value would a control variable be correlated or uncorrelated with the policy variable? The lab asks us to "warm-up" by drawing a venn diagram using the correlation matrix in the lab instructions. If there are any asterisks in the correlation box does that mean it is correlated (significant enough) and would thereby overlap the policy variable in our venn diagram? If my understanding is correct, ND is correlated with PSS and RSE, but NOT CSE. Is that correct? Please see the image for reference. 

Correlation Matrix Question:
![image](https://github.com/Watts-College/paf-510-template/assets/146388467/1a9807e7-1b8a-4512-aeac-69d7a53d8b4a)

Lab 4 Question in instructions NOT in rmd: 
![image](https://github.com/Watts-College/paf-510-template/assets/146388467/19f51ddf-f103-4e1e-9cd6-ddd6d6dc5e42)

Lab 4 RMD:
![image](https://github.com/Watts-College/paf-510-template/assets/146388467/1e7e2891-a68c-4545-a18e-82f32f3a642a)

**Comment by swest235** [comment]
@AntJam-Howell should the magnitude of bias always be a percentage? In part 3 in the lab I got -11.4, which seems wrong, but I believe I am calculating everything correctly.

**Comment by AntJam-Howell** [comment]
Hi @swest235, 
Correct, the RMD is the final authority, you are only responsible for answering questions in the RMD.  

Yes, your intuition is correct.  In a correlation matrix, the value of a control variable being correlated or uncorrelated with the policy variable depends on the correlation coefficient. Generally:

A correlation coefficient close to 1 or -1 indicates a strong correlation.
A coefficient around 0 suggests no correlation.

If there are asterisks in the correlation box between the control variable and the policy variable, it implies a statistically significant correlation. In a Venn diagram, this would mean the circles representing these variables should overlap to some extent. The degree of overlap would visually represent the strength of the correlation (more overlap for stronger correlations).
