### ISSUE TITLE
Lab 4 - Question 2 - Part 3: What exactly is this asking? 

### ISSUE THREAD

**Issue by swest235** [Watts-College/paf-510-template#33]
@AntJam-Howell Can you please clarify what this question is asking us? 

"Explain the direction of bias in this model using the formula for omitted variable bias: what must be true about the sign of the correlation between RSE and CSE to get these results?"

**Comment by KaytieS** [comment]
@swest235 I think it is asking about whether the sign of a1 is negative or positive, so since the direction of bias of the model is negative and B2 is positive, this means that the a1 value must be negative, since bias = a1* B2.

**Comment by AntJam-Howell** [comment]
@swest235 @KaytieS, 
Yes, correct interpretation.  Since a1 is negative and B2 is positive the sign of the bias has to be negative.

**Comment by swest235** [comment]
@AntJam-Howell @KaytieS Thank you for the clarification. I am afraid I am still misunderstanding something here. 

I do understand, within the context of the question, that IF a1 represents the correlation between CSE and RSE (-0.44); and if B2 represents the correlation between RSE and SWB (0.60), then we'd get a negative. However, what I don't get, is why a1 and B2 in this context is different than a1 and B2 when we calculated them earlier in the lab. Using the table below, don't we end up with both positive B2 and a1? a1 = 1.78 (+), B2 = .32? 

![image](https://github.com/Watts-College/paf-510-template/assets/146388467/e55fea95-23f5-4b41-9ca9-b7a3936a8e87)

**Comment by swest235** [comment]
Thank you both for the clarification. @AntJam-Howell @KaytieS
