### ISSUE TITLE
Lab 4 - Question 1 - Part 3: Magnitude of Bias

### ISSUE THREAD

**Issue by swest235** [Watts-College/paf-510-template#34]
@AntJam-Howell  should the magnitude of bias always be a percentage? In part 3 in the lab I got -11.4, which seems wrong, but I believe I am calculating everything correctly. 

How do we explain that in terms of overall bias? The example in the readings had a percentage, which made more sense. 

For reference:
B1 = -0.05
b1 = 0.52
Bias = 0.57

Magnitude of Bias = Bias/B1 = .57/-.05 = -11.4

![image](https://github.com/Watts-College/paf-510-template/assets/146388467/6417c9d0-1291-46cf-bbe1-c046d4aee47d)

**Comment by AntJam-Howell** [comment]
Hi @swest235, 
the calculation is correct, and the -11.4 indicates that when we omit PSS, our coefficient on ND is off by a magnitude of 11.4, or roughly 1100% !
