### ISSUE TITLE
Lab 6 grade not posted

### ISSUE THREAD

**Issue by chrisogino** [Watts-College/paf-510-template#38]
Hi,
I saw the announcement of lab 6 grades, but mine has not been posted.

I submitted it before the deadline. Is it still pending something or will it be posted later without further intervention?

Thanks,
Christopher Ogino

**Comment by AntJam-Howell** [comment]
Hi @chrisogino 
Because you submitted all labs 1-5 and received perfect score, the 6th lab points will not count towards the grade.  This is because the syllabus mentions the labs are worth 50 points total (10 points each).   

Best
