### ISSUE TITLE
Lab 01 Q7 + Review session recordings

### ISSUE THREAD

**Issue by tnt2501** [Watts-College/paf-510-template#4]
Hello professor,
For question 7 on lab 1 it says to calculate R squared. I see in the Lewis-Beck text - Rsquared = RSS/TSS. 

In the lecture notes, building a regression model. Rsquared=.282, but to calculate that would be to tale 13507 (ESS) / 47977 (TSS).

I am confused on how in the lecture notes they got that answer for Rsquared. 

Also, you mentioned the review sessions are recorded, where can I find the recordings at?

Thank you!

**Comment by youngjaewon** [comment]
@tnt2501 

Hi Tyler,
The confusion arises from the different definitions of those terms in the Lecture Note and Lewis-Back's textbook. In the Lecture Note, RSS stands for Residual Sum of Squares, and ESS stands for Explained Sum of Squares. However, in Lewis Back's textbook, RSS refers to Regression (explained) sum of squares, and ESS refers to Error (unexplained) sum of squares. Therefore, the RSS and ESS in the Lecture Note are equivalent to Lewis Back's ESS and RSS, respectively. Good catch!

The recording of Review Session 1 can be found in the most recent announcement or right here: https://www.dropbox.com/scl/fi/9bthnshy1e93zkatqc3jr/PAF510-Rev1.mp4?rlkey=inrumc07b00t37hzyongahmvt&dl=0

**Comment by tnt2501** [comment]
Thank you that clears some things up. So for the lab I would want to take the 48.4/TSS in order to obtain Rsquared?

In other words, Rsquared = regression (explained) sum of squares / total sum of squared , is that correct?

**Comment by youngjaewon** [comment]
That is correct!

**Comment by tnt2501** [comment]
Awesome, thanks again!

**Comment by lecy** [comment]
I'm not sure where the [course handouts](https://watts-college.github.io/cpp-523-fall-2021/resources/) ended up in Canvas, but one of them highlights some of the variations in statistics notation across texts. It mentions the ESS and RSS challenge: 

https://github.com/DS4PS/cpp-523-spr-2020/raw/master/handouts/Common-Statistics-Notation.pdf

There is no universal notation in statistics, unfortunately!
