### ISSUE TITLE
Lab 4 - Part 2 (Auxiliary Code)

### ISSUE THREAD

**Issue by kalanicook** [Watts-College/paf-510-template#41]
Hi Professor, can the calculations for bias in part 1 and part 2 of the question be slightly different?

In part 1 of the question, I identified B1 as (-0.05) and b1 as (0.52); therefore, if  bias = b1 - B1 than 0.52 -(-0.05) = 0.57. 

![Screen Shot 2024-06-12 at 12 34 59 PM](https://github.com/Watts-College/paf-510-template/assets/172541373/84a88325-56ee-4a9b-a8fd-684e0140a148)

In part 2 of the question where we are asked to create our own auxiliary model in R, I wrote (m.auxiliary <- lm( PSS ~ ND, data=dat). From the graph presented, after calculating, I got bias = 0.5792.

![Screen Shot 2024-06-12 at 12 34 59 PM](https://github.com/Watts-College/paf-510-template/assets/172541373/8f374f4e-99a7-4393-b959-5e7e63b5a316)

Is the issue that my auxiliary model is incorrect? 

Thank you!

**Comment by JasonSills** [comment]
@kalanicook 

It looks like you provided an your calculation for part 2? What was the code and math that you used?

**Comment by JasonSills** [comment]
@kalanicook 

It looks like you pasted the same image twice, so I'm not able to see the calculation in the second. This is likely a rounding error.

**Comment by kalanicook** [comment]
@JasonSills - sorry about that! 

Here is the second image:
![Screen Shot 2024-06-12 at 12 34 48 PM](https://github.com/Watts-College/paf-510-template/assets/172541373/7ffae2df-1a26-4b60-9f3a-d5ba5aff57ce)

When running (m.auxiliary <- lm( PSS ~ ND, data=dat), the slope became 1.81.

Therefore, I multiplied a1 (1.81) by B2 (0.32) and got an output of 0.5792.

**Comment by JasonSills** [comment]
@kalanicook 

This is due to rounding since we are only looking at two decimal places. .57 is very close to .5792.

**Comment by kalanicook** [comment]
@JasonSills - thank you for the help!
