### ISSUE TITLE
Lab 01 Submission Question: Can we submit our work as a separate PDF or did you want everything in the word document?

### ISSUE THREAD

**Issue by reed441** [Watts-College/paf-510-template#42]
Can we submit our handwritten work as a separate PDF or does everything have to be in the word document? Just want to make sure I submit this correctly!

**Comment by nickmcmullen** [comment]
@reed441 either is fine for this lab. If you're going to use handwritten notes to show your work, just make sure it's legible!

**Comment by nickmcmullen** [comment]
@reed441 now that lab 1 is done would you mind closing out this issue so we keep the forum tidy? Thanks!
