### ISSUE TITLE
General Question: Will there be opportunities for weekly review sessions?

### ISSUE THREAD

**Issue by linh-luong** [Watts-College/paf-510-template#43]
Hello,
I was wondering if there are opportunities to have weekly review sessions on top of office hours? Thank you!

**Comment by nickmcmullen** [comment]
@linh-luong there are currently no weekly review sessions scheduled. I'd encourage you to engage with your classmates and instructors on the issue tracker first and schedule office hours after that you need additional support. Office hours are by appointment and can be set up with me via email or Canvas PM.

**Comment by jteles24** [comment]
Hi,

I sent you message through canvas, not sure if it reached you but I am trying to schedule office hours for additional help

**Comment by jteles24** [comment]
@linh-luong Hi im Jessica and Im also looking for help maybe we can work together if at all possible

**Comment by nickmcmullen** [comment]
@jteles24 I saw your message to Dr. Howell. Please review M0 and M1 lecture materials and post your questions on the issue tracker first. The course is meant to be self-contained, meaning everything you need to complete the assignments is available in the lecture materials. If you are still stuck after reviewing the lecture materials and posting in the issue tracker - you can email me or send me a PM in Canvas to schedule office hours. It also looks like several of your classmates are starting a study group (see the Study Group Thread in the issue tracker) - I recommend you join them and pose your questions there too.

**Comment by jteles24** [comment]
Hi,


Thanks for replying! How can I set up a office hour/zoom meeting? For extra
help. Never ever have worked or even done anything with R and i have read
the material but need additional help

**Comment by nickmcmullen** [comment]
@jteles24 I totally understand your hesitation being new to R. Do you have a specific R-related question? Let's start by posting that as a new issue in the issue tracker. I'll review it and if we cannot resolve, we will schedule office hours. It's important to try to first address questions on the issue tracker because the whole class will have an opportunity to benefit from it.

**Comment by nickmcmullen** [comment]
@linh-luong to keep the forum tidy can you please close this issue out? Thanks!
