### ISSUE TITLE
I don't think I'm calculating something correctly

### ISSUE THREAD

**Issue by vairving** [Watts-College/paf-510-template#45]
Hi, I must admit I'm trying to shake loose the cobwebs. I've gone through the various readings, equations and done the math, but I as I get to the end it seems my answers aren't correct. It would be helpful to speak with someone to see where I might be missing a step in the process. For question one, it's a simple cov (x,y) / var (x). For 3, I have a feeling I'm messing up here. The mean of y is given, along with the mean of x, we solved for b1 in question 1, should be simple but I'm not too confident in my answer. How can I go about speaking with someone? @AntJam-Howell  @nickmcmullen Thank you!

**Comment by ashleywilk** [comment]
Hi, did you get any responses? 

I just finished all the way to question 7, however my sum sq and mean sq do not match the table provided! 
The values I found for b1 and b0 are below 
b1 = 1.1 
b0 = -0.6

**Comment by bgreene15** [comment]
Hi,
I got the same answers as Ashley for slope and intercept. 
@ashleywilk Try re-doing Y-hat with the slope and intercept you found above and the X value given in the table. Following that e = Y - Y-hat.  This should help for question 5. Question 6 use the values found with Y-hat and the mean of Y. Hope this helps!

**Comment by matillm2** [comment]
Hi! I am got nearly the same answers as above (1.1, 0.6) and not able to make a match with the ANOVA table. Since I am so close to time, I submitted the assignment as is; I'd like to send my assignment to someone to help me with my mistake? will it be ok to post it here after the deadline, or what is the procedure for that? Thanks!  @AntJam-Howell @nickmcmullen

**Comment by nickmcmullen** [comment]
@vairving @ashleywilk @matillm2 appreciate you posting your questions here. We will post solutions to the lab after the due date has passed. You'll be able to go back and ensure you've answered all questions correctly and also review concepts from the module there. Once we have done that, if you still are confused about a concept you are welcome to reach out to schedule office hours.

For those of you getting hung up on sum of squares:

- Think of total sum of squares (TSS) as cumulative squared difference between every actual data point Y(i) and the mean of Y (Y-bar)
 
- Think of explained sum of squares (ESS, also referred to as regression sum of squares) as the cumulative squared difference between every predicted value of Y (Y-hat, from the regression model) and the mean (Y-bar).

- Think of residual sum of squares (ResidualSS) as the cumulative squared difference between every actual data point Y(i) and every predicted value of Y (Y-hat, from the regression model).

I encourage you to revisit Section 4.1 of the M1 lecture notes - which also explains this concept in a similar way. There is also a visual that I find really helpful covering explained/unexplained variance in Section 4.2.1 of the M1 lecture notes, too.

**Comment by vairving** [comment]
Alright everyone, I slept on it and realized I made a simple mistake. Your responses helped me see where I messed up. I'd encourage everyone to be mindful of your positives and negatives. Thanks!!

**Comment by matillm2** [comment]
Ack - yep I've figured mine out now too. Doh! I had two numbers flipflopped toward the beginning - fixed that one thing now it matches the anova table!
