### ISSUE TITLE
R issue

### ISSUE THREAD

**Issue by jteles24** [Watts-College/paf-510-template#46]
Hi guys,

So as im trying to do the readings and looking ahead on how to submit lab 2 is everyone understanding how to even start this lab. Im so lost on the technical side. Plus after reviewing the solutions i was more confused once i saw it in R

please help

**Comment by nickmcmullen** [comment]
@jteles24 have you installed R and RStudio yet? That's the first step. If you are in the Program Evaluation and Data Analytics track, the program handbook should have guidance on all required software and how to install it.

**Comment by jteles24** [comment]
Yes, I did.

But its so confusing. I am begging you for a 1:1 meet

**Comment by nickmcmullen** [comment]
@jteles24 send me an email and we can schedule

**Comment by nickmcmullen** [comment]
@jteles24 if you're all set can you close out this issue to keep the forum tidy? Thanks!
