### ISSUE TITLE
Lab 2 in R

### ISSUE THREAD

**Issue by jteles24** [Watts-College/paf-510-template#47]
Hi guys Im back so after downloading the R template, I see the questions but for example are suposed to just type our answer in or is there a code step to run the visual ** part of the question that has to also be done

**Comment by merima-d** [comment]
Hi jteles24, hope my answer helps - I typed the answers in R, and once you answered all questions click on 'Knit' and you'll get the 'html' format that should be saved with your name and the lab# on one of your local folders. 

But before that, run the entire template and knit it so you'll see the regression table as a reference in the html format. I also was not able to see it  by running it only in the designating chunks.  You don't need to write the code for it.

**Comment by jteles24** [comment]
Thank you so much! I really appreciate it this . I will work on it tonight
again.

**Comment by nickmcmullen** [comment]
@merima-d thanks for chiming in
@jteles24 hopefully that's what you needed to get started. Let us know how it goes as you start working your way through Lab 02.

**Comment by nickmcmullen** [comment]
@jteles24 now that Lab 02 has passed can you close out this issue to keep the forum tidy? Thanks!
