### ISSUE TITLE
Program Impact Lecture

### ISSUE THREAD

**Issue by ligonza9** [Watts-College/paf-510-template#48]
Hi everyone! I am just checking for understanding. When the confidence interval goes through the null hypothesis, that means it's not statistically significant, correct? For example on page 28, program 1 on the left would not be significant? 

![Screenshot 2024-08-31 172725](https://github.com/user-attachments/assets/d0a4cfd5-29e2-4a10-b05b-76f93005dbde)

**Comment by nickmcmullen** [comment]
@ligonza9 you're on the right track

**Comment by nickmcmullen** [comment]
@ligonza9 if you don't have any follow up questions here can you close this issue out to keep the forum tidy? Thanks!
