### ISSUE TITLE
How do I get the mean from the table given?

### ISSUE THREAD

**Issue by mnsimon** [Watts-College/paf-510-template#50]
I am struggling to find the mean from the data table given. I am trying to plug it into my CI equation for question 2 however I cannot seem to figure it out despite re-reading lab1 and 2 for help. So far I have my  CI (u)= X bar +- 1.96 (given) * SE (Question 1 answer). 
Thanks in advance!

**Comment by ashleywilk** [comment]
If you reference LAB 2 instructions I think you will find the answer to your question there, there is a description of the table and values with the notations.

**Comment by nickmcmullen** [comment]
@mnsimon double check what kind of confidence interval you're looking for in Q2 - sample mean or slope. Those are two different formulas requiring two different inputs (x-bar vs. b1). You can find a roadmap of how these two formulas are derived on p. 20 of p-04-confidence-intervals.pdf in the lecture materials

**Comment by mnsimon** [comment]
I am at a complete loss, I am trying to solve for Q2. I have now solved for CI of the slope however, I do not know what to do with that information. I tried plugging what I know into Y= b0 + b1X + e1 however I do not know X or 
Y. Do I have to solve the CI for slope and for mean?

**Comment by nickmcmullen** [comment]
@mnsimon check out this thread... https://github.com/Watts-College/paf-510-template/issues/54

Make sure you're using the right confidence interval formula. In this case we are looking for the slope CI. Plugging in the values you know already from the regression model table (SE & b1) will give you the upper and lower bounds.

**Comment by nickmcmullen** [comment]
@mnsimon now that Lab 02 has passed can you close out this issue to keep the forum tidy? Thanks!
