### ISSUE TITLE
Question regarding showing work in Lab 2

### ISSUE THREAD

**Issue by dmkoch9978** [Watts-College/paf-510-template#52]
Hello,

I was just working through Lab 2 when I found that it asks for us to "Draw the three confidence intervals to see how they change as a result of the controls included in the model." in Q5, do we need to draw them and add it to the rmd document if it's already provided in the questions above?

Also, in the next question, it says "pairs plot for reference for Q6." Do we need to do anything with the plots? I didn't use them to answer the question so I'm not sure what to do with them.

Thanks!
Dani

@AntJam-Howell 
@nickmcmullen

**Comment by ashleywilk** [comment]
Hello, I believe in Q5 we need to illustrate to show how the slope changes between the 3 models. 
I am also curious about the wording of Q6!

**Comment by nickmcmullen** [comment]
@dmkoch9978 @ashleywilk 

In the lab template RMD, Q5 is a bit more specific than just "draw them"  - please make sure to read it all the way through. For drawing, it's ok as long as you have the confidence intervals drawn and visible in Q2-4. The most important takeaway from that question is understanding which model has the largest (absolute value) slope and smallest standard error. Wrapping your head around those concepts will make sure you're in a good spot on the confidence intervals concept.

For Q6 the pairs plot is just to help you see the relationships between all the variables. You don't necessarily need it to answer the question, but it's a helpful aid to seeing how the variables are related. Q6 is more about understanding the concept of slope in univariate regression vs. multivariate regression.

**Comment by nickmcmullen** [comment]
@dmkoch9978 now that Lab 02 has passed can you close this issue out to keep the forum tidy? Thanks!

**Comment by dmkoch9978** [comment]
Yes of course. Sorry about that!
