### ISSUE TITLE
Calculating Confidence Interval for Lab 2

### ISSUE THREAD

**Issue by dmkoch9978** [Watts-College/paf-510-template#54]
Hello,

For lab 2, do we need to actually calculate the confidence interval for Q2-4? I used the visuals for my answers but it's just now occurring to me that I may actually need to use the equations we've been given in lecture.

Thanks,
Dani

@AntJam-Howell 
@nickmcmullen

**Comment by nickmcmullen** [comment]
@dmkoch9978 it's important that you understand the underlying math for calculating confidence intervals from slope and SE. I recommend using the formulas from the lecture and showing your work.

**Comment by pathernz** [comment]
@nickmcmullen Besides the RMD/HTML, may we do the calculations by hand and import as PDF to show the math?

**Comment by nickmcmullen** [comment]
@pathernz that's fine, but you shouldn't need to. You can just type the values into the formula to show you understand how to use it.

**Comment by jteles24** [comment]
Hi Im also having trouble how to write the formula in R

**Comment by nickmcmullen** [comment]
@jteles24 @pathernz 
You both are comfortable with the below formulas from the lecture notes. And you know the values from the model tables, so just plug them in to calculate the confidence intervals. 

Upper bound = b1 + SE*(t)
Lower bound = b1 - SE*(t)

<img width="947" alt="Screenshot 2024-09-03 at 7 09 54 PM" src="https://github.com/user-attachments/assets/f45108fb-be09-4ef3-b01b-33d73ae75cf3">

**Comment by jteles24** [comment]
Thank you very much

**Comment by jteles24** [comment]
very confused on question 5 not clear to me

**Comment by nickmcmullen** [comment]
@jteles24 the lab RMD template has a more specific question in Q5 with regard to slope and SE for the three models you drew CIs in Q2-4
