### ISSUE TITLE
Naming RSS inconsistency

### ISSUE THREAD

**Issue by merima-d** [Watts-College/paf-510-template#55]
On page 15 of p-02-partitioning-variance.pdf, there is : 

"RSS (regression sum of squares)
TSS (total sum of squares)
ESS (error sum of squares)
* Note that sometimes RSS stands for
“residual” SS and ESS sometimes for
“explained” SS"

I thought that ESS always stands for not-explained variance or residuals. Please clarify the 'Note' part for me. I hope it's an innocent typing error. Thank you.

**Comment by nickmcmullen** [comment]
@merima-d good call out. Regression sum of squares and explained sum of squares are the same thing. If you're unsure about what you're communicating with the abbreviations, best to spell it out. If there is a portion of the lecture materials where an abbreviation is used and it's unclear which it is, post it here and I can clarify.
