### ISSUE TITLE
Final Exam Schedule

### ISSUE THREAD

**Issue by pathernz** [Watts-College/paf-510-template#57]
Hello,

Just looking ahead at schedules - how long will the Final Exam be open to be taken/when is it due?
I cannot see the dates on the syllabus or course summary.

Thank you kindly.

@nickmcmullen

**Comment by nickmcmullen** [comment]
@pathernz  the final exam will open on October 5th and will remain open through October 9th at 11:59 PM AZ time. You are required to complete it on your own and may not discuss it with other students. I'll make a post about it in Canvas as we get closer.
