### ISSUE TITLE
Module 4 link to 'Crack baby'

### ISSUE THREAD

**Issue by merima-d** [Watts-College/paf-510-template#58]
I have a difficulty to access the link to the article ' Crack baby' without subscribing to the issuer. Please advise.

**Comment by lecy** [comment]
There's an archived version here: https://github.com/Watts-College/paf-510-template/blob/main/pubs/crack-vs-poverty.pdf

**Comment by merima-d** [comment]
Got it. Thank you.






On Friday, September 6, 2024 at 04:01:47 PM EDT, Jesse Lecy ***@***.***> wrote: 







There's an archived version here: https://github.com/Watts-College/paf-510-template/blob/main/pubs/crack-vs-poverty.pdf
