### ISSUE TITLE
Question on Lab 3 question 2

### ISSUE THREAD

**Issue by norah90** [Watts-College/paf-510-template#59]
Hello,
I am having issues understanding question two. I was able to create the scatterplot on test score and teacher quality, while saving the residuals.
My created scatterplot has a clear downward slope, but I am thinking that it should match the scatterplot from last week if we are regressing the test scores AND keeping the teacher quality residuals? 
Or is the scatterplot created in lab 3 including test scores, teacher quality residuals, and removing the explained portion? 
Thank you,

<img width="637" alt="Screenshot 2024-09-08 at 12 22 57 PM" src="https://github.com/user-attachments/assets/e4d39994-880d-474d-b96e-d9631a2153d0">

@nickmcmullen

**Comment by nickmcmullen** [comment]
@norah90 You're using the wrong scatterplot as your baseline. Test Score & Class Size should be your baseline - note the negative slope, which is also what you create in Q1 of Lab 03. Then, you effectively "control" for the effect of Teacher Quality by regressing test ~ tqual and plotting the residuals of Test Score (when regressed on Teacher Quality) and Class Size. 

Q2 wants to make sure you understand the difference - why did the scatterplots change? What does it tell you about the relationship between Teacher Quality, the policy variable (Class Size), the the outcome (Test Score)?

**Comment by norah90** [comment]
Okay I see now, thank you for the clarification!
