### ISSUE TITLE
Lab 2 question

### ISSUE THREAD

**Issue by leachapman019** [Watts-College/paf-510-template#6]
Hello!
I just wanted to ask about the confidence interval. How are we supposed to know if our answers are statistically significant? Are we supposed to create a null hypothesis and compare it to that? Thank you!

**Comment by jasminacosta** [comment]
Hi! 

From my understanding when you have the models for the confidence intervals you can tell which ones are statistically significant when they DO NOT cross the null hypothesis (0) which is the vertical line on the model. However, if it does cross that line then it is not statiscally significant. In the notes it shows examples of this. 

I was confused at first too, but I was able to get the help I needed. 

I hope this helped! :)
