### ISSUE TITLE
Lab 3 Question 2

### ISSUE THREAD

**Issue by ligonza9** [Watts-College/paf-510-template#60]
Hello ~ 

For lab 3 question 2 do we need to solve for the bivariate regression using Y = b0 + b1•X + e ? That would mean we first need to solve for b1 and b0? Or are we supposed to just look at the scatterplots and compare the strength of the relationship? 

Thanks for your help!

**Comment by nickmcmullen** [comment]
@ligonza9 For Q2 create a scatterplot following the instructions and describe why the relationship changed from the baseline model. It's important that you understand and explain what that means about the relationship between Teacher Quality and Test Score (outcome)/Class Size (policy variable).

**Comment by ligonza9** [comment]
@nickmcmullen Thank you so much for the clarification. Also related, but not for the assignment... in the video, it said that software is required to solve the multi-variable linear equation. Is this because it's easier that way and can lead to less errors?

**Comment by nickmcmullen** [comment]
@ligonza9 Software is what you'll use in almost all real-world applications. This course is about building a thorough understanding of the theory behind regression models, then when you use software to build more advanced models, you'll understand why the output looks the way it does, feel comfortable interpreting it, and can draw meaningful and mathematically correct conclusions from it.
