### ISSUE TITLE
Lab 3 Q1

### ISSUE THREAD

**Issue by dmkoch9978** [Watts-College/paf-510-template#61]
Hello,

Question 1 asks us to create a scatterplot, however, the scatterplot is already provided for us underneath that question. It looks like there isn't actually an answer or action necessary for that question. Am I correct in that assumption?

-Dani

@AntJam-Howell
@nickmcmullen

**Comment by nickmcmullen** [comment]
@dmkoch9978 yes, the code is already provided for Q1. Note there are a few code lines commented out in the chunk suggesting ways to adjust the parameters of the scatterplot to make it more visually pleasing. Not required, but there if you want to try it.

**Comment by dmkoch9978** [comment]
Thanks!
