### ISSUE TITLE
Lab Assignment 4 Raw HTML Code RStudio 4.3.2

### ISSUE THREAD

**Issue by alizea-alvarez** [Watts-College/paf-510-template#62]
@nickmcmullen @AntJam-Howell 

I'm using the Rstudio (version 4.3.2) app on my Windows laptop. When running my code for Part 1 Question 1, the output renders as raw HTML instead of displaying the actual table. I clicked open the template provided and haven't changed anything from the top of the document page. What can I do to render the actual table?
![Screenshot 2024-09-12 211730](https://github.com/user-attachments/assets/aa2b66b7-b0ca-41e8-af2d-7fac479ab85e)

**Comment by nickmcmullen** [comment]
@alizea-alvarez the chunk options results = 'asis' generates HTML code that should render into a nice table when you knit. Try it and let me know what you see.

**Comment by cekuhlma** [comment]
@alizea-alvarez I was having the same problem and changed the type ='html' to type='text' and was able to see the chart.  Not sure if that will help.
