### ISSUE TITLE
Coefficient Statistical Significance

### ISSUE THREAD

**Issue by alizea-alvarez** [Watts-College/paf-510-template#63]
@AntJam-Howell @nickmcmullen 

How do we know if our coefficient of the policy variable is statistically significant? Is it always tied to the standard error, or is there a way to tell just by looking at how it changes when we introduce the control variable? In Lab 4 Question 2 Part 1, the standard error stayed the same, but the coefficient's sign changed and got smaller. Are we supposed to plot the confidence intervals for the model and determine statistical significance that way? I'm trying to figure out how to proceed.

Thanks!

**Comment by nickmcmullen** [comment]
@alizea-alvarez in the regression output tables the asterisks next to the coefficients indicate the level of statistical significance (if any).
