### ISSUE TITLE
Lab 4 "m.auxiliary" error

### ISSUE THREAD

**Issue by pathernz** [Watts-College/paf-510-template#65]
Hello,

I am getting the following error. Template works fine when those lines are removed but would like to know how to fix. 

Thank you kindly 

<img width="601" alt="Screenshot 2024-09-13 at 9 49 15 PM" src="https://github.com/user-attachments/assets/b22358e0-b5f2-4162-b729-8928d11cdf41">
 @nickmcmullen

**Comment by nickmcmullen** [comment]
@pathernz that error means you're running code that requires the object m.auxiliary but that object doesn't exist. Check back to Q1 pt. 2 to see if you've defined m.auxiliary properly.
