### ISSUE TITLE
Lab 4 Questions in General

### ISSUE THREAD

**Issue by alizea-alvarez** [Watts-College/paf-510-template#67]
@nickmcmullen @AntJam-Howell 

In theory, Network Diversity (ND) would lose significance when Perceived Social Support (PSS) was added because the standard error would increase due to their high correlation. However, my table above shows that when I include PSS in my model, ND's standard error decreases from 0.20 to 0.19, suggesting it becomes more precise while accounting for the omitted variable bias of a correlated variable. I don't understand how this happens with a correlated variable. I thought uncorrelated variables decreased the standard error. So, I don't know how ND has lost significance. How do we measure significance if the standard error decreases or stays the same when including the correlated control variable? If it's lost significance, how can we tell?

**Comment by nickmcmullen** [comment]
@alizea-alvarez as you noted ND and PSS are correlated, which means the presence of PSS will affect the slope of ND. So while the SE of the slope of ND decreases slightly when we compare m.naive and m.full, the slope also changes. Note how close the ND slope in m.full is to 0. This means we'd need a much smaller SE than 0.19 to get a statistically significant result. You can calculate the confidence intervals for the slope of ND in both m.naive and m.full by hand if you want to confirm the statistical significance.
