### ISSUE TITLE
Ballentine Diagram Question

### ISSUE THREAD

**Issue by norah90** [Watts-College/paf-510-template#68]
Hello,
I am trying to draw out the Ballentine Diagram to have a better understanding of question 2. 
I understand that SWB is the dependent variable, but looking at the matrix- what data is needed to be looked at to know what the policy variable is in regards to RSE, CSE and ND?
thank you, 

@nickmcmullen

**Comment by nickmcmullen** [comment]
@norah90 you can infer what the policy question is by reading the language in Q2. "How does our need for approval of others (contingent self-esteem) impact our happiness (SWB)?" Which variable is the outcome? Which variable are we assessing the impact of on the outcome?

**Comment by norah90** [comment]
thank you!
