### ISSUE TITLE
Mini Assessment 3 Question

### ISSUE THREAD

**Issue by bjames25221** [Watts-College/paf-510-template#70]
I did not complete the Module 3 Mini Assessment before it closed, can you provide the question(s) or access to the quiz so that I can use it to check my learning/prepare for the final exam? I can see the previous two assessments because I completed them before they were due. @nickmcmullen @AntJam-Howell

**Comment by nickmcmullen** [comment]
@bjames25221 I reopened the quiz through Friday so you can take it. Please note you still won't receive credit for completing it.
