### ISSUE TITLE
Module 5 Template

### ISSUE THREAD

**Issue by jteles24** [Watts-College/paf-510-template#72]
Hi is there a template for R for module 5 it doesnt appear to be in the lab instructions.

**Comment by linh-luong** [comment]
You can choose to create your own rmd file or MS word for Lab 5.

Also @nickmcmullen , can we submit our answers in pdf with our work showing similar to Lab 1?

**Comment by nickmcmullen** [comment]
@jteles24 either RMD or word/PDF works for Lab 05

@linh-luong there isn't a ton of in-depth math here, just typing out the formulas, showing you understand where to apply the right dummy variables, and interpreting them accurately. Considering that, I'd prefer these be typed so your work and answers are all in the same place. There's an example of how to type/format the regression formulas with dummy variables in the lab instructions. If you absolutely must write it out, I'll still accept it. The most important thing is you demonstrate you understand the concepts.

**Comment by jteles24** [comment]
thank you
