### ISSUE TITLE
Lab 5: File Location

### ISSUE THREAD

**Issue by aaron13g** [Watts-College/paf-510-template#73]
Hi,

I wanted to start Lab 5 and was wondering where the file is. I've looked in the materials for it and cannot find a downloadable file like we have had in the prior weeks

**Comment by ligonza9** [comment]
I think for this lab you get to choose if you will submit as an RMD or Word file. 

"Submission Instructions
After you have completed your lab submit via Canvas. Login to the ASU portal at http://canvas.asu.edu/ and navigate to the assignments tab in the course repository. Upload your file to the appropriate lab submission link. You can use an RMD file or an MS Word file for this assingment.

Remember to name your files according to the convention: Lab-##-LastName.xxx"

**Comment by nickmcmullen** [comment]
@aaron13g, @ligonza9 is correct. This question was also asked in this previously closed issue here https://github.com/Watts-College/paf-510-template/issues/72

**Comment by aaron13g** [comment]
> I think for this lab you get to choose if you will submit as an RMD or Word file.
> 
> "Submission Instructions After you have completed your lab submit via Canvas. Login to the ASU portal at http://canvas.asu.edu/ and navigate to the assignments tab in the course repository. Upload your file to the appropriate lab submission link. You can use an RMD file or an MS Word file for this assingment.
> 
> Remember to name your files according to the convention: Lab-##-LastName.xxx"

Thank you
