### ISSUE TITLE
lab 5 Hypothesis Question

### ISSUE THREAD

**Issue by alizea-alvarez** [Watts-College/paf-510-template#74]
@nickmcmullen @AntJam-Howell 

Are the coefficients representing whether there is a difference in the dependent variable (salary) between the reference category and the included category (male and female) regardless of the other dummy variable (minority status)? Or are the coefficients saying that the corresponding categorical variable (female) significantly impacts the dependent variable compared to the reference category(male)?

**Comment by nickmcmullen** [comment]
@alizea-alvarez I can't directly answer your question without answering the lab question for you. The lecture materials have several relevant examples including very similar to this lab question. Try looking through Hypothesis Testing with Groups Part-01 handout and the lab practice questions provided in M5.
