### ISSUE TITLE
Lab 6, Q1- Very Small Inc. Sq. Coefficient

### ISSUE THREAD

**Issue by bjames25221** [Watts-College/paf-510-template#77]
Is anyone else seeing a very small x^2 coefficient when they run the regression for Question 1? I have to go 9 digits out to get a non-zero. @nickmcmullen @AntJam-Howell 

![image](https://github.com/user-attachments/assets/ac084935-492f-4272-a166-286920e22986)

**Comment by SagarChandra07** [comment]
This might help:This file might fix it

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
I put the necessary dlls in the archive

**Comment by bjames25221** [comment]
Sorry but what did you put in the file to help fix it? I can't imagine I'm so far off I have to download a new file.

**Comment by bjames25221** [comment]
Disregard, I read the rest of the lab instructions.

**Comment by thelabcat** [comment]
> Sorry, @SagarChandra07, but what did you put in the file to help fix it? I can't imagine I'm so far off I have to download a new file.
> 
> 

Do not run that file! It is malware. The account has been spamming links to it all over GitHub. They use a password protected zip archive to evade the auto-check by MediaFire. I extracted it on a non-Windows machine and checked it manually. 17 positives. Been searching through their comments and warning people.

**Comment by bjames25221** [comment]
@thelabcat hahah yea, I thought leaving a file on a transfer site as an answer was a red flag. I didn’t download, but thanks for the confirmation!
