### ISSUE TITLE
Lab 6 Q2: Wrong Looking Results

### ISSUE THREAD

**Issue by bjames25221** [Watts-College/paf-510-template#78]
I'm using the scaled model (/10,000) as recommended in the lab, and I'm using 15k and 25k as inputs for question 2, but my output doesn't look correct. 

Currently, I'm getting that a person is 27 points LESS HAPPY when they get an income raise from 15k to 25k. I'm getting similarly strange answers (all negative) for Q3 and Q4, increasing in absolute value and outside of the scale (in the -400s).

Below is my code from Q2 (almost exactly what is on the lab instructions), can someone provide input on what I'm getting wrong?

![image](https://github.com/user-attachments/assets/0ecb957c-08c7-483c-8902-b576c3457464)

@nickmcmullen @AntJam-Howell

**Comment by bjames25221** [comment]
* I just tried to use the unscaled version of the coefficients and got what looks like a much better answer. I'd still appreciate feedback/an explanation of why it comes out incorrectly given the code above.

**Comment by jslandes** [comment]
@bjames25221  If you copy/paste and run the chunk exactly as it is in the lab instructions (with the dummy 1s), the output is 410. So I'm thinking the lecture isn't showing the exact answer to check against, but rather what the output should look like if the code runs correctly

**Comment by merima-d** [comment]
I'm also confused about this because it doesn't make any sense that there is a negative relationship between income increase and happiness at the early stage.  Later, the level of happiness should start slowly decreasing given the same rate of increase as at the start of one's career. Should we divide 15000/10000 and  25000/10000  which turns the values to be 1.5 and 2.5 respectively?

**Comment by nickmcmullen** [comment]
@bjames25221 15000/10000 is not 15, it's 1.5. Double check your scaled coefficients and try again

**Comment by nickmcmullen** [comment]
@merima-d you scaled the coefficients correctly. Now plug them into the regression formula and subtract happy.25k from happy.15k to get the change in happiness.

**Comment by bjames25221** [comment]
@nickmcmullen got it! Thank you, it does work with those values. In this case, the lab instructions set up the problem incorrectly. The instructions show 15 and 25 for Q2 and tell you to rescale to $15000 and $25000 if you didn't scale the coefficients.
