### ISSUE TITLE
Lab 6, Q2/lecture notes clarification

### ISSUE THREAD

**Issue by jslandes** [Watts-College/paf-510-template#79]
I have a question about the notes. I think I could be misinterpreting this portion.

>**_Effects of Adding Units or Subtracting are Nonsymmetrical_**
>Also note that if you are in a classroom with ten students, then the effect of adding a student will not be the same as the effect of removing a student.
>
>ABS((Y^|X=5)−(Y^|X=4))  does not equal ABS((Y^|X=4)−(Y^|X=5))

I read this statement as saying the _effect/output_ for change of 1 unit is not equal to the _effect/output_ for change of -1 unit because the starting position and direction matter in a quadratic regression. But I assumed that the calculation estimating effect is always ABS(Y^|X=starting unit)−(Y^|X=changed unit).

I tried to calculate ABS(Y^|X=15000)−(Y^|X=25000) by hand and got -6.35459, which is not what I expected to see since the article says the relationship between money and happiness is positively correlated at least until people hit $75,000. Although there is variance, so this could be a valid result.

However, the instructions for Lab 6, Q2 has us run happy.25k - happy.15k. This output is positive, which makes more sense but is contrary to my understanding of the notes.

Any guidance would be much appreciated! If I did misunderstand the lecture notes, does it mean (in a real-world scenario where the vertex or a graph isn't already given), that I should calculate the vertex, min, and max first to figure out which number goes where based on the shape? Does this sign ever change to a plus (like if the parabola opens upwards)?

@nickmcmullen @AntJam-Howell

**Comment by nickmcmullen** [comment]
@jslandes what you're describing from the lecture notes is that the relationship between dependent and independent variables is not linear. We can't expect the rate of change at one point to be the same at another point along the curve. For the lab, you're on the right track. Subtracting happy.25k - happy.15k describes the change from 15K to 25K.
