### ISSUE TITLE
Lab 6 Q1

### ISSUE THREAD

**Issue by norah90** [Watts-College/paf-510-template#82]
Hello,
Im having some issues understand where we edit the code for question 1 for this weeks homework assignment. I replaced x & y with happiness and income, but am not sure where the square comes into play. 
Below is what I have so far:
<img width="445" alt="Screenshot 2024-09-30 at 3 36 57 PM" src="https://github.com/user-attachments/assets/f79799d4-bb9b-4f76-b529-4bfc5d28584c">

The lab notes give us additional code than what is in the template, is the lm code what we need to add to our code in R? when I add that code it gives me an error that "Error in eval(predvars, data, env) : object 'y.happy' not found" any guidance on where I am going wrong is appreciated, thank you 

<img width="618" alt="Screenshot 2024-09-30 at 3 35 04 PM" src="https://github.com/user-attachments/assets/0a564048-55e7-4aaa-8eca-63c2f3772b54">

@nickmcmullen @AntJam-Howell

**Comment by nickmcmullen** [comment]
@norah90 the error is saying you didn't define y.happy. Make sure it's defined before you run the quadratic regression. The lab instructions have a block of code that shows you how to do this.
