### ISSUE TITLE
Lab 6, Part 2, Q2: Type I or Type II Error?

### ISSUE THREAD

**Issue by bjames25221** [Watts-College/paf-510-template#84]
On Part II, Question 2, it asks us what the likely impact of Point B has on the regression line. Based on Point B's placement, there are two feasible answers for this:

![image](https://github.com/user-attachments/assets/682671f0-a3e0-4874-a1f4-1ae0aa36e8d4)

1) Pulls Down the Slope
Point B sits close to the center of the data on the x-axis, but far lower than the expected value on the y-axis. Because of how close it is to the center on the x-axis, it pulls the full slope down. This presents Type II error because it increases the model's Standard Error and misrepresents the true impact of the revenue (logged) on the director salary (logged), creating a false negative.

2) Exaggerates the Slope
Point B sits slightly left of the data's center on the x-axis. This pulls down the left side of the regression line, exaggerating the slope and making it look like there is a higher impact of revenue (logged) on director salary (logged). In this case, it presents Type I error because it makes the slope look greater, creating a false positive.

Is one of these answers more correct than the other? Can it do both things at once, or should we always look to reduce the answer down to a specific impact when looking at outliers?

@AntJam-Howell @nickmcmullen

**Comment by nickmcmullen** [comment]
@bjames25221 the two impacts you listed are mutually exclusive - a single outlier can't cause the slope to both increase and decrease at the same time. If you were to visualize rotating the regression line on its axis to be closer to intersecting with Point B, would the slope of the line increase or decrease?

**Comment by bjames25221** [comment]
@nickmcmullen I may have misspoken on my part 1 above. I understand it doesn’t cause the slope to both increase (steepen) and decrease (flatten) those would obviously be mutually exclusive.

Based on the lecture materials, it could have caused the slope to step down. For example if the constant was 6, it would be 5.5 now because of how central the outlier is on the x-axis. I think has the impact of increasing the standard error.

It is also far enough left to steepen the slope, making the revenue (logged) look like it has greater impact on salary (logged) than it does.

![image](https://github.com/user-attachments/assets/8faed269-8dcf-488b-be91-08b51acd634c)

It looks similar to both of the circled cases above from the lecture notes.

My questions are:
- Can it do both of those things at once?

- If not, how do we determine which effect it has from just looking at the graph?

- Because it looks like both of those cases (or somewhere in between), how do we determine which type of error it would present?

**Comment by nickmcmullen** [comment]
@bjames25221 yes, an outlier can both bias the slope and shift the regression line vertically depending on where it's positioned. The closer the outlier is along the x-axis to the center of the data, the less it will bias the slope and the more it's likely to shift the regression line, depending on how far away from the mean it is along the y-axis.  Part 2 Q1 & 2 are only asking about the impact of the outliers on slope and which type of error it will contribute to, so don't overthink it too much. While Point B is closer to the center of the data on the x-axis than Point A, it's still offset slightly. Based on the lecture materials (and screenshot you shared above), would you say that will bias the slope? Which direction (e.g. which type of error will that bias contribute to)?
