### ISSUE TITLE
Lab 06 Part II, Q4 coefficients

### ISSUE THREAD

**Issue by cgeffner** [Watts-College/paf-510-template#87]
![image](https://github.com/user-attachments/assets/1c7d05ab-8b4f-441c-92e8-fcc6dd07cd2e)

In the markdown document and in the instructions the coefficients on stargazer the table and in the equation don't coincide. Shouldn't they be the same, or am I terribly misunderstanding something?

**Comment by bjames25221** [comment]
The lab code pulls 2000 random datapoints (rows) from the whole dataset (65000 rows), so the coefficients are going to vary a little bit each time we run the code chunks. I used the given ones (6.367 and .343) to calculate Q4.

**Comment by cgeffner** [comment]
That makes a lot of sense, thank you James!
